### ISSUE TITLE
geos and proj zip files are removed

### ISSUE THREAD

**Issue by BenStW** [aaronrenner/heroku-buildpack-rgeo-prep#2]
you proposed to include these zip files
https://s3.amazonaws.com/spacialdb/heroku/geos-3.3.8.tar.gz
https://s3.amazonaws.com/spacialdb/heroku/proj-4.8.0.tar.gz

But they are not accessible anymore: NoSuchBucket
Any idea where to get them from?

**Comment by kashif** [comment]
They are back and I have updated geos:

https://s3.amazonaws.com/spacialdb/heroku/geos-3.4.2.tar.gz
https://s3.amazonaws.com/spacialdb/heroku/proj-4.8.0.tar.gz

**Comment by aaronrenner** [comment]
I just updated the readme to point to the new geos url. Thanks @BenStW for pointing out the issue and @kashif for fixing the urls.
